[TASK]Setup tailwindcss
itsmeurbi/medical_control_rails pull request #4
Opened 2021-11-25 05:29 UTC by Diezagu

I recently setup tailwindcss :) please don't be aggressive with your comments. Peace!

2021-11-25 14:55 UTC, itsmeurbi requested changes
Let's add it as a js dependency instead.
This gem uses `tailwindcss 2.2.15`, so we better use latest stable version(2.2.16)

2021-11-25 14:59 UTC, itsmeurbi commented
You can follow Tailwind official setup guide: https://tailwindcss.com/docs/installation
You will probably experiences a [PostCSS 8 issue compatibility](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build), let's try updating to v8 first

2021-11-25 21:34 UTC, bryanmg approved these changes
LGTM!

2021-12-05 07:15 UTC, Diezagu commented
I have already changed the setup of tailwindcss as a js dependency :)

2021-12-11 02:36 UTC, itsmeurbi requested changes

2021-12-11 02:36 UTC, itsmeurbi commented on Gemfile
> +gem "tailwindcss-rails", "~> 0.5.1"
If tailwind was added as a js package, then there's no need for a gem

2021-12-13 16:20 UTC, itsmeurbi requested changes
I don't thinks this is the right way t do it.
<img width="1552" alt="Screen Shot 2021-12-13 at 10 18 28" src="https://user-images.githubusercontent.com/26292224/145848783-6bf7c5e7-25f4-4725-8e6a-46097d87b023.png">

2021-12-13 16:20 UTC, itsmeurbi commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
Why do we need this?

2021-12-13 16:20 UTC, itsmeurbi commented on app/views/layouts/application.html.erb
> +    <main class="container mx-auto mt-28 px-5 flex">
No needed at the moment. We haven't discuss anything about designs

2021-12-27 22:21 UTC, itsmeurbi commented
@Diezagu since we got rid of node dependencies, we need to add Tailwind in a different way. I just created [another PR](https://github.com/itsmeurbi/medical_control_rails/pull/12) doing that.

2021-12-27 22:21 UTC, itsmeurbi commented
Closing this PR due to comment [here](https://github.com/itsmeurbi/medical_control_rails/pull/4#issuecomment-1001782169)

2021-12-27 22:21 UTC, closed without merging