[TASK]Setup of postgresql done
itsmeurbi/medical_control_rails pull request #7
Opened 2021-12-06 02:31 UTC by Diezagu

I have changed the database system to PostgreSQL :)

2021-12-07 05:53 UTC, bryanmg approved these changes

2021-12-11 02:38 UTC, itsmeurbi requested changes

2021-12-11 02:38 UTC, itsmeurbi commented on config/database.yml
> +  database: db/development
Let's use a more descriptive db name. Maybe something like medial_control_env:
(i.e. medial_control_development, medial_control_test and medial_control_production)

2021-12-13 14:48 UTC, itsmeurbi approved these changes

2021-12-13 16:25 UTC, itsmeurbi requested changes
You didn't complete the installation process. Missing changes on Gemfile.lock
`bundle install` pending

2021-12-14 15:02 UTC, itsmeurbi requested changes
Ok, now PR seems to be legit. But it should be one single commit.
Take a look at how [rebase interactive](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history) works

2021-12-20 19:44 UTC, itsmeurbi approved these changes
Seems to be legit!

2021-12-20 19:45 UTC, merged